### ISSUE TITLE
The "Armor Filters" page loads very slowly

### ISSUE THREAD

**Issue by cridus** [3dots/EROptimizer#7]
Can you please make the loading asynchronous, so that the site doesn't freeze? It takes several seconds to load >.<
Thanks

**Comment by 3dots** [comment]
So it's not actually the app that's freezing. It's the browser struggling to render all the sets with all the buttons.
Short of only rendering a limited number of sets, I don't know what else can be done. If I do that though, I'd also need to add a "search" field, otherwise how do you find a particular piece to disable? I'd also need to somehow create Prev/Next buttons, or make scroll dynamically add more records and hide previous ones... it's a lot of work.

**Comment by cridus** [comment]
I remember that it was much faster in the past though... welp.

**Comment by 3dots** [comment]
_One eternity later..._

I made the autocompletes default state use the same list instead of creating 4 lists of the same data.

![image](https://user-images.githubusercontent.com/6589306/216023286-0a5929a4-6579-42f9-a504-9c3b2df47264.png)

Maybe that will help?

I couldn't really spot a difference myself back in November, that's why I am committing this only now.

If you're still using the tool, let me know if it helps.

**Comment by cridus** [comment]
Yeah, it's faster now 🎉 But why is that tab slow every time an not only the first time?

**Comment by 3dots** [comment]
Because I think when you switch views, angular garbage collects the view, which includes the autocompletes that have the lists.

I think I am going to close this for now. Who knows, if DLC adds 100 more armor sets, then I'll have to do overhaul the rendering not to put all the records, but don't think I have the resolve to do it now.
